name: Deploy endeavour.today

on:
    push:
        branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:            
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            cd src
            # set subscription
            az account set --subscription "Pay-As-You-Go"
            # upload
            az storage blob upload-batch --account-name endeavourtoday -d '$web' -s .
            # purge endpoint
            az cdn endpoint purge --content-paths  "/*" --profile-name "endeavourtoday-main" --name "endeavourtoday" --resource-group "endeavour.today"
    - name: logout
      run: |
            az logout
